### ISSUE TITLE
stopped working, terminal true fixes it?

### ISSUE THREAD

**Issue by ElMoonLite** [sanduhrs/phpstorm-url-handler#13]
Everything worked for a few months, but suddenly it stopped working.
(ubuntu 16.04 LTS)

I managed to "fix" it by editing `phpstorm-url-handler.desktop` and changing to `Terminal=true`, then run `sudo desktop-file-install phpstorm-url-handler.desktop` and `sudo update-desktop-database` again, and now everything works.

If I leave everything unchanged (from current repo) and only change that true/false I can toggle between it working and not working. Not sure why. It does not seem like it should make a difference. I only made that change to see output and try to debug it, but apparently it had the side effect of making it work.

The downside is that I see a terminal window pop up for a second (which is a bit annoying), but at least it is working again.

Not really a neat fix, but good enough for me. Perhaps it can help someone else using this.

**Comment by seybsen** [comment]
~I tried to fix it with `Terminal=true` but this only works for me if phpstorm is not already running.~

nevermind... it somehow works now :smile:

**Comment by sanduhrs** [comment]
Appears to be solved?!
