### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Kolbasyatin** [sanduhrs/phpstorm-url-handler#7]
Doesn't work for me. 
The reason is that Symfony profiler generates link without "line" in address, so, regular expression doesn't work properly.

I wrote something like this
`(.*?)file(\:\/\/|\=)(.*?)(&line=(\d+))?$` ,  it works [here](https://regex101.com/r/ZsVF7A/1), but it isn't work in sed expression .
Somebody know why Symfony profiler stoped generate lines in this one ?

**Comment by alexbusu** [comment]
I had another issue 
```
Traceback (most recent call last):
  File "/usr/local/bin/phpstorm", line 108, in <module>
    start_new_instance(ide_args)
  File "/usr/local/bin/phpstorm", line 103, in start_new_instance
    os.execv(RUN_PATH, [bin_file] + args)
OSError: [Errno 2] No such file or directory
```
because of _buggy_ `phpstorm` executable.
So letting only the "pstorm block" worked for me. 
```bash
#...

# Check if phpstorm|pstorm command exist.
#if type phpstorm > /dev/null; then
#    /usr/bin/env phpstorm --line "${line}" "${file}"
#elif type pstorm > /dev/null; then
    /usr/bin/env pstorm --line "${line}" "${file}"
#fi
```

**Comment by dereuromark** [comment]
I had the same issue, at least in FF (quantum).

**Comment by sanduhrs** [comment]
Is this still an issue?

**Comment by sanduhrs** [comment]
Add additional support for /folder/file:row syntax in 0244a56b926e94faddc319a9298c1ac096763822
